#!/bin/bash

command -v lolcat >/dev/null 2>&1 || { echo >&2 "I require lolcat but it's not installed.  Aborting."; exit 1; }
command -v figlet >/dev/null 2>&1 || { echo >&2 "I require figlet but it's not installed.  Aborting."; exit 1; }

if [[ $# -ne 1 ]]; then
    echo "Illegal number of parameters. This scipt expects 1 parameter (a number)"
    exit 1
fi

N=$1; 
while [[ $((--N)) > 0 ]]; do 
        echo "$N" | figlet -c | lolcat && sleep 1; 
done

timeout 5 speaker-test -t sine -f 500 > /dev/null

exit 0
