#!/bin/bash
# get size of the things in the directory
if [[ $# -ne 1 ]]; then
    echo "Illegal number of parameters. This scipt expects 1 parameter (a path)"
    exit 1
fi

du -h -d 1 "$1" | sort -rh

