#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Illegal number of parameters. This scipt expects 1 parameter (a number)"
    exit 1
fi

N=$1; 
while [[ $((--N)) > 0 ]]; do 
        echo $N | figlet -c | lolcat && sleep 1; 
done

speaker-test -t pink -f 500 -P 2 > /dev/null

exit 0
